In [1]:
import numpy as np
import torch 

# In this tutorial we are trying to use custom dataset to predict the crops yields for apple and orange ( target variables )
# Considering Temp, raifall and humidiy (input variable )

## yield_apple = w11 * temp + w12 * rainfall + w13 * humidity + b1

## yield_orange= w21 * temp + w22 * rainfall + w23 * humidity + b2

## Training Data

In [2]:
# input (temp, rainfall, humidity )

In [4]:
inputs = np.array([ [ 73,67,43 ],
                    [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]                  
                  ], dtype='float32')

In [5]:
#Target variables ( apples, oranges)
target = np.array([[56,70], [81,101],[119,133],[22,37],[103,119]], dtype='float32')

In [7]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [8]:
target

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [9]:
#Convert inputs and targetsto tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(target)

In [11]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [13]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

##  Initialize weight and bias

In [16]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

In [17]:
w

tensor([[-1.5473,  0.5842,  0.5340],
        [-0.1562,  0.3747, -0.6844]], requires_grad=True)

In [18]:
b

tensor([-1.5795,  0.5361], requires_grad=True)

In [19]:
def model(x):
    """ x * Transpose of W + b"""
    return x @ w.t() + b

In [23]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum( diff * diff ) / diff.numel()

## 1. Generate Prediction
## 2. Calculate the loss
## 3. Computer gradient with respect to weights and biases
## 4. Adjust weight by subtract 
## 5. rest gradient to zero

In [24]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*1e-5
        b-=b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()
        

In [25]:
preds

tensor([[ 53.8656,  73.5257],
        [ 81.3688,  94.0096],
        [125.8988, 142.9373],
        [  3.5721,  54.2944],
        [110.3703,  97.5739]], grad_fn=<AddBackward0>)

In [26]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])